Added processing of multiple endpoints
SlavZ27/sky.pro.store pull request #19
Opened 2023-02-15 19:44 UTC by evnag

feat: added processing POST localhost:8080/ads/{ads_pk}/comments
feat: added processing POST localhost:8080/ads/{ads_pk}/comments/{id}
feat: added processing GET localhost:8080/ads/{ads_pk}/comments/{id}
feat: added processing GET localhost:8080/ads/{ads_pk}/comments
feat: added mapping logic to ResponseWrapperCommentDto in the CommentMapper class
feat: added CommentNotFoundException
feat: added http-client dependency to pom.xml for PATCH tests

2023-02-16 08:55 UTC, SlavZ27 requested changes

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/controller/AdsApiController.java
>      public ResponseEntity<ResponseWrapperCommentDto> getComments(@Parameter(in = ParameterIn.PATH, description = "", required = true, schema = @Schema()) @PathVariable("ad_pk") String adPk) {
Сделай лучше сразу Integer adPk. Тогда проверкой значения будет заниматься Spring

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/controller/AdsApiController.java
>      public ResponseEntity<CommentDto> addComments(@Parameter(in = ParameterIn.PATH, description = "", required = true, schema = @Schema()) @PathVariable("ad_pk") String adPk, @Parameter(in = Paramete
Сделай лучше сразу Integer adPk. Тогда проверкой значения будет заниматься Spring

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/controller/AdsApiController.java
>      public ResponseEntity<CommentDto> getComments(@Parameter(in = ParameterIn.PATH, description = "", required = true, schema = @Schema()) @PathVariable("ad_pk") String adPk, @Parameter(in = Paramete
Сделай лучше сразу Integer adPk. Тогда проверкой значения будет заниматься Spring

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/controller/AdsApiController.java
>      public ResponseEntity<CommentDto> updateComments(@Parameter(in = ParameterIn.PATH, description = "", required = true, schema = @Schema()) @PathVariable("ad_pk") String adPk, @Parameter(in = Param
Сделай лучше сразу Integer adPk. Тогда проверкой значения будет заниматься Spring

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/exception/AdsNotFoundException.java
> +public class AdsNotFoundException extends RuntimeException {
Посмотри как было. Было с настройкой @ResponseStatus(HttpStatus.NOT_FOUND) и наследование от NotFoundException

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/exception/CommentNotFoundException.java
> +
@ResponseStatus(HttpStatus.NOT_FOUND) и наследование от NotFoundException

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +    private final AdsRepository adsRepository;
Зачем в CommentService AdsRepository?

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +        Ads ads = adsRepository.findById(adsId).orElseThrow(() -> {
Эта проверка уже была в AdsService

2023-02-16 08:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +        Ads ads = adsRepository.findById(adsId).orElseThrow(() -> {
Эта проверка уже была в AdsService

2023-02-16 19:00 UTC, evnag commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +    private final AdsRepository adsRepository;
> Зачем в CommentService AdsRepository?

нам нужны ads в этом сервисе

2023-02-16 19:02 UTC, evnag commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +        Ads ads = adsRepository.findById(adsId).orElseThrow(() -> {
> Эта проверка уже была в AdsService

тогда нужно передавать объект ads в параметры, т.к. его нужно сетить в коммент

2023-02-16 19:03 UTC, evnag commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +        Ads ads = adsRepository.findById(adsId).orElseThrow(() -> {
тогда нужно передавать объект ads в параметры, т.к. его нужно сетить в коммент

2023-02-16 19:18 UTC, nadillustrator approved these changes

2023-02-16 19:19 UTC, nadillustrator approved these changes

2023-02-16 19:20 UTC, nadillustrator approved these changes

2023-02-17 04:55 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +//        if(createAdsDto == null)// какие здесь нужны проверки??
Наверное никакие. Если только не проверки полей

2023-02-17 04:59 UTC, SlavZ27 approved these changes

2023-02-17 04:59 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/service/impl/AdsServiceImpl.java
> +        ads.setImages(images);
тут, кажется, лишнее. в этом поле будет лист и без присваивания

2023-02-17 04:59 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/service/impl/CommentServiceImpl.java
> +        Ads ads = adsRepository.findById(adsId).orElseThrow(() -> {
тогда нужно, да

2023-02-17 04:59 UTC, merged