Create repositories
SlavZ27/sky.pro.store pull request #8
Opened 2023-02-10 21:08 UTC by nadillustrator

2023-02-12 14:46 UTC, SlavZ27 commented on src/main/java/ru/skypro/homework/repository/CityRepository.java
> +public interface CityRepository extends JpaRepository<CityRepository, Integer> {
Уже не нужный репозиторий

2023-02-12 14:47 UTC, SlavZ27 requested changes
Прошу удалить CitiRepository в связи с последними событиями

2023-02-12 15:15 UTC, SlavZ27 approved these changes

2023-02-13 07:35 UTC, evnag approved these changes

2023-02-13 09:01 UTC, merged